/***************************************************************
 *
 * Interactive Demo: Digital Image Properties and Processing
 * Copyright (c) 2006 Dr. Andrew Kwok-Fai LUI
 * The Open University of Hong Kong
 *
 * Enhance the learning effectiveness of students through greater interactions
 */
/*  This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package faifai.image;

import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.swing.JDialog;
import javax.swing.JFrame;

public class HistogramPanel extends javax.swing.JPanel {

  private static final int TYPE_AVERAGE = 0;
  private static final int TYPE_RED = 0;
  private static final int TYPE_GREEN = 0;
  private static final int TYPE_BLUE = 0;
  private JDialog dialog = null;
  private JFrame frame;
  private int averageArray[] = new int[256];
  private int redArray[] = new int[256];
  private int greenArray[] = new int[256];
  private int blueArray[] = new int[256];

  /** Creates new form HistogramPanel */
  public HistogramPanel() {
    initComponents();
  }

  private void initArray() {
    for (int i = 0; i < 256; i++) {
      averageArray[i] = redArray[i] = greenArray[i] = blueArray[i] = 0;
    }
  }

  private void updateHistogram(BufferedImage image) {
    if (image == null) {
      initArray();
      return;
    }
    int width = image.getWidth();
    int height = image.getHeight();
    double sum[] = new double[3];
    for (int x = 0; x < width; x++) {
      for (int y = 0; y < height; y++) {
        int pixel = image.getRGB(x, y);
        int alpha = (pixel >> 24) & 0xff;
        int red = (pixel >> 16) & 0xff;
        int green = (pixel >> 8) & 0xff;
        int blue = (pixel) & 0xff;
        int avg = (red + green + blue) / 3;
        averageArray[avg]++;
        redArray[red]++;
        greenArray[green]++;
        blueArray[blue]++;
      }
    }
  }

  public void showDialog(BufferedImage image) {
    showDialog(image, "Histogram");
  }

  public void showDialog(BufferedImage image, String title) {
    if (dialog == null) {
      frame = new JFrame();
      dialog = new JDialog(frame, false);
      dialog.getContentPane().add(this);
      dialog.setSize(320, 240);
      dialog.setTitle(title);
    } else {
    }
    updateHistogram(image);
    histogramLabel1.setPlotColor(Color.WHITE);
    histogramLabel1.setData(averageArray);
    histogramLabel2.setPlotColor(Color.RED);
    histogramLabel2.setData(redArray);
    histogramLabel3.setPlotColor(Color.GREEN);
    histogramLabel3.setData(greenArray);
    histogramLabel4.setPlotColor(Color.BLUE);
    histogramLabel4.setData(blueArray);
    dialog.setVisible(true);
    this.repaint();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    histogramLabel1 = new faifai.image.HistogramLabel();
    histogramLabel2 = new faifai.image.HistogramLabel();
    histogramLabel3 = new faifai.image.HistogramLabel();
    histogramLabel4 = new faifai.image.HistogramLabel();
    jButton1 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(0, 0, 0));
    setLayout(new java.awt.GridBagLayout());

    histogramLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Average Histogram", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 10), new java.awt.Color(255, 255, 255))); // NOI18N
    histogramLabel1.setMinimumSize(new java.awt.Dimension(160, 60));
    histogramLabel1.setPreferredSize(new java.awt.Dimension(160, 60));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(histogramLabel1, gridBagConstraints);

    histogramLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Red", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 10), new java.awt.Color(255, 255, 255))); // NOI18N
    histogramLabel2.setMinimumSize(new java.awt.Dimension(160, 60));
    histogramLabel2.setPreferredSize(new java.awt.Dimension(160, 60));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(histogramLabel2, gridBagConstraints);

    histogramLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Green", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 10), new java.awt.Color(255, 255, 255))); // NOI18N
    histogramLabel3.setMinimumSize(new java.awt.Dimension(160, 60));
    histogramLabel3.setPreferredSize(new java.awt.Dimension(160, 60));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(histogramLabel3, gridBagConstraints);

    histogramLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 10), new java.awt.Color(255, 255, 255))); // NOI18N
    histogramLabel4.setMinimumSize(new java.awt.Dimension(160, 60));
    histogramLabel4.setPreferredSize(new java.awt.Dimension(160, 60));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(histogramLabel4, gridBagConstraints);

    jButton1.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
    jButton1.setText("Close");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closeActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    add(jButton1, gridBagConstraints);

    jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText("Average");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
    add(jLabel1, gridBagConstraints);

    jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Red");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
    add(jLabel2, gridBagConstraints);

    jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Green");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
    add(jLabel3, gridBagConstraints);

    jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Blue");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
    add(jLabel4, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
    dialog.setVisible(false);
  }//GEN-LAST:event_closeActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private faifai.image.HistogramLabel histogramLabel1;
  private faifai.image.HistogramLabel histogramLabel2;
  private faifai.image.HistogramLabel histogramLabel3;
  private faifai.image.HistogramLabel histogramLabel4;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  // End of variables declaration//GEN-END:variables
}
