/***************************************************************
 *
 * Interactive Demo: Digital Image Properties and Processing
 * Copyright (c) 2006 Dr. Andrew Kwok-Fai LUI
 * The Open University of Hong Kong
 *
 * Enhance the learning effectiveness of students through greater interactions
 */
/*  This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package faifai.image;

import helper.gui.SplashScreenFrame;
import helper.gui.TutorialFrame;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class LowPassDemo extends javax.swing.JFrame {

  /** Creates new form RotationHoleDemo */
  public LowPassDemo() {
        try {
            javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (Exception ex) {
        }
    initComponents();
    loadImage();
    try {
      TutorialFrame tutorialFrame = new TutorialFrame();
      tutorialFrame.loadText("/tutorial/LowPassDemo.htm");
      tutorialFrame.showFrame();
    } catch (Exception ex) {
    }
  }

  private void loadImage() {
      String resname = "/sampleimages/GuessWho2.jpg";
      InputStream istream = super.getClass().getResourceAsStream(resname);
      try {
        BufferedImage image = ImageIO.read(istream);
        source = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = source.createGraphics();
        g2d.drawImage(image, 0, 0, null);
        imageLabel1.setImage(source);
      } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, ex, "Image Read Error", JOptionPane.ERROR_MESSAGE);
      }
  }

  private void closeApplication() {
    int result = JOptionPane.showConfirmDialog(this, "Are you sure to quit?", "Confirm", JOptionPane.OK_CANCEL_OPTION);
    if (result == JOptionPane.CANCEL_OPTION) {
      return; /* The Cancel button is pressed */
    }
    System.exit(0);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    imageLabel1 = new faifai.image.ImageLabel();
    jPanel2 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenu3 = new javax.swing.JMenu();
    jMenuItem4 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Aliasing and Low Pass Demo");
    setBackground(new java.awt.Color(0, 0, 0));
    setMinimumSize(new java.awt.Dimension(320, 280));
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jPanel1.setBackground(new java.awt.Color(0, 0, 0));
    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Original", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(255, 255, 255))); // NOI18N
    jPanel1.setMinimumSize(new java.awt.Dimension(280, 340));
    jPanel1.setPreferredSize(new java.awt.Dimension(280, 340));
    jPanel1.setLayout(new java.awt.GridLayout(1, 0));

    imageLabel1.setMinimumSize(new java.awt.Dimension(128, 128));

    javax.swing.GroupLayout imageLabel1Layout = new javax.swing.GroupLayout(imageLabel1);
    imageLabel1.setLayout(imageLabel1Layout);
    imageLabel1Layout.setHorizontalGroup(
      imageLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 266, Short.MAX_VALUE)
    );
    imageLabel1Layout.setVerticalGroup(
      imageLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 337, Short.MAX_VALUE)
    );

    jPanel1.add(imageLabel1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(jPanel1, gridBagConstraints);

    jPanel2.setBackground(new java.awt.Color(0, 51, 102));
    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel2.setMinimumSize(new java.awt.Dimension(128, 128));
    jPanel2.setPreferredSize(new java.awt.Dimension(128, 128));
    jPanel2.setLayout(new java.awt.GridBagLayout());

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton1.setText("Apply Low Pass Filter");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
    jPanel2.add(jButton1, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(jPanel2, gridBagConstraints);

    jMenuBar1.setBackground(new java.awt.Color(102, 0, 102));

    jMenu1.setBackground(new java.awt.Color(102, 0, 102));
    jMenu1.setForeground(new java.awt.Color(255, 255, 255));
    jMenu1.setText("File");
    jMenu1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

    jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 10));
    jMenuItem2.setText("Quit");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem2quitActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem2);

    jMenuBar1.add(jMenu1);

    jMenu3.setBackground(new java.awt.Color(102, 0, 102));
    jMenu3.setForeground(new java.awt.Color(255, 255, 255));
    jMenu3.setText("About");
    jMenu3.setFont(new java.awt.Font("Tahoma", 0, 10));

    jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jMenuItem4.setText("Multimedia Learning Platform");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem4aboutActionPerformed(evt);
      }
    });
    jMenu3.add(jMenuItem4);

    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents
  private BufferedImage source;
  private BufferedImage processed = null;
  private boolean isApplied = false;

    private void jMenuItem2quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2quitActionPerformed
      closeApplication();
}//GEN-LAST:event_jMenuItem2quitActionPerformed

    private void jMenuItem4aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4aboutActionPerformed
      //printInformation();
      SplashScreenFrame.showFrame("/SplashScreenImageProcessing.png");
}//GEN-LAST:event_jMenuItem4aboutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      isApplied = !isApplied;
      if (isApplied) {
        if (processed == null) {
          processed = ImageOperator.blur(source);
          for (int i=0; i<14; i++) {
          processed = ImageOperator.blur(processed);
          }
        }
        imageLabel1.setImage(processed);
        jButton1.setBackground(Color.YELLOW);
      } else {
        imageLabel1.setImage(source);
        jButton1.setBackground(Color.WHITE);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new LowPassDemo().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private faifai.image.ImageLabel imageLabel1;
  private javax.swing.JButton jButton1;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
